"""Remove FK constraints to external tables

Revision ID: 0169d13429da
Revises: 3978ae1aa548
Create Date: 2025-11-02 18:14:12.941077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0169d13429da'
down_revision: Union[str, Sequence[str], None] = '3978ae1aa548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_candidate_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('jobs_company_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('jobs_category_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('jobs_created_by_id_fkey'), 'jobs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('jobs_created_by_id_fkey'), 'jobs', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('jobs_category_id_fkey'), 'jobs', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('jobs_company_id_fkey'), 'jobs', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('applications_candidate_id_fkey'), 'applications', 'users', ['candidate_id'], ['id'])
    # ### end Alembic commands ###
