"""Add embedding columns to jobs table

Revision ID: da5b3d52c35f
Revises: 0169d13429da
Create Date: 2025-11-05 17:27:12.427328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da5b3d52c35f"
down_revision: Union[str, Sequence[str], None] = "0169d13429da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column(
            "embedding", sa.JSON(), nullable=True, comment="384-dim embedding vector"
        ),
    )
    op.add_column(
        "jobs",
        sa.Column("embedding_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "embedding_updated_at")
    op.drop_column("jobs", "embedding")
    # ### end Alembic commands ###
